CREATE TABLE department (
  Id SERIAL PRIMARY KEY,
  Name VARCHAR(60) DEFAULT NULL
);

CREATE TABLE seller (
  Id SERIAL PRIMARY KEY,
  Name VARCHAR(60) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  BirthDate TIMESTAMP NOT NULL,
  BaseSalary DOUBLE PRECISION NOT NULL,
  DepartmentId INT NOT NULL,
  FOREIGN KEY (DepartmentId) REFERENCES department(Id) ON DELETE CASCADE
);
